export enum skillEnum {
    // Programming Languages
    JavaScript = 'JavaScript',
    TypeScript = 'TypeScript',
    Python = 'Python',
    Java = 'Java',
    C = 'C',
    CPlusPlus = 'C++',
    CSharp = 'C#',
    Go = 'Go',
    Rust = 'Rust',
    Ruby = 'Ruby',
    PHP = 'PHP',
    Swift = 'Swift',
    Kotlin = 'Kotlin',
    R = 'R',
    Bash = 'Bash',
    Dart = 'Dart',
    Scala = 'Scala',
    Haskell = 'Haskell',
  
    // Frontend Development
    HTML = 'HTML',
    CSS = 'CSS',
    Sass = 'Sass',
    Less = 'Less',
    React = 'React',
    Angular = 'Angular',
    Vue = 'Vue',
    Svelte = 'Svelte',
    Tailwind = 'Tailwind CSS',
    Bootstrap = 'Bootstrap',
    NextJS = 'Next.js',
    NuxtJS = 'Nuxt.js',
    jQuery = 'jQuery',
    Vite = 'Vite',
    ThreeJS = 'Three.js',
    D3JS = 'D3.js',
  
    // Backend Development
    NodeJS = 'Node.js',
    ExpressJS = 'Express.js',
    NestJS = 'NestJS',
    Django = 'Django',
    Flask = 'Flask',
    FastAPI = 'FastAPI',
    SpringBoot = 'Spring Boot',
    Laravel = 'Laravel',
    ASPNET = 'ASP.NET',
    RubyOnRails = 'Ruby on Rails',
    Phoenix = 'Phoenix (Elixir)',
    GraphQL = 'GraphQL',
    RESTAPI = 'REST API',
    gRPC = 'gRPC',
    WebSockets = 'WebSockets',
  
    // Databases
    MySQL = 'MySQL',
    PostgreSQL = 'PostgreSQL',
    MongoDB = 'MongoDB',
    Redis = 'Redis',
    SQLite = 'SQLite',
    OracleDB = 'Oracle DB',
    MicrosoftSQL = 'MS SQL Server',
    Firebase = 'Firebase',
    Cassandra = 'Cassandra',
    Neo4j = 'Neo4j',
    Elasticsearch = 'Elasticsearch',
  
    //  DevOps & Cloud
    Git = 'Git',
    GitHub = 'GitHub',
    GitLab = 'GitLab',
    Docker = 'Docker',
    Kubernetes = 'Kubernetes',
    Jenkins = 'Jenkins',
    CI_CD = 'CI/CD',
    GitHubActions = 'GitHub Actions',
    Terraform = 'Terraform',
    Ansible = 'Ansible',
    AWS = 'AWS',
    Azure = 'Microsoft Azure',
    GoogleCloud = 'Google Cloud Platform',
    DigitalOcean = 'DigitalOcean',
    Heroku = 'Heroku',
  
    // Cybersecurity
    EthicalHacking = 'Ethical Hacking',
    PenetrationTesting = 'Penetration Testing',
    NetworkSecurity = 'Network Security',
    ApplicationSecurity = 'Application Security',
    Cryptography = 'Cryptography',
    OWASP = 'OWASP',
    SIEM = 'SIEM',
    IDS_IPS = 'IDS/IPS',
    Firewalls = 'Firewalls',
    Wireshark = 'Wireshark',
    BurpSuite = 'Burp Suite',
    Metasploit = 'Metasploit',
  
    // Networking
    TCPIP = 'TCP/IP',
    DNS = 'DNS',
    DHCP = 'DHCP',
    Routing = 'Routing',
    Switching = 'Switching',
    VPN = 'VPN',
    ProxyServers = 'Proxy Servers',
    NetworkMonitoring = 'Network Monitoring',
    Cisco = 'Cisco',
    MikroTik = 'MikroTik',
    LinuxNetworking = 'Linux Networking',
  
    // Operating Systems
    Windows = 'Windows',
    Linux = 'Linux',
    Ubuntu = 'Ubuntu',
    CentOS = 'CentOS',
    RedHat = 'Red Hat',
    MacOS = 'macOS',
    Unix = 'Unix',
    AndroidOS = 'Android OS',
    iOS = 'iOS',
  
    // Data, AI & ML
    DataAnalysis = 'Data Analysis',
    DataScience = 'Data Science',
    MachineLearning = 'Machine Learning',
    DeepLearning = 'Deep Learning',
    ReinforcementLearning = 'Reinforcement Learning',
    NLP = 'Natural Language Processing',
    ComputerVision = 'Computer Vision',
    TimeSeries = 'Time Series Analysis',
    TensorFlow = 'TensorFlow',
    PyTorch = 'PyTorch',
    ScikitLearn = 'Scikit-learn',
    Pandas = 'Pandas',
    NumPy = 'NumPy',
    Matplotlib = 'Matplotlib',
    Seaborn = 'Seaborn',
    OpenCV = 'OpenCV',
    HuggingFace = 'Hugging Face',
    MLFlow = 'MLFlow',
    ApacheSpark = 'Apache Spark',
    Jupyter = 'Jupyter Notebook',
  
    // UI/UX & Design
    Figma = 'Figma',
    AdobeXD = 'Adobe XD',
    Sketch = 'Sketch',
    InVision = 'InVision',
    UIUXDesign = 'UI/UX Design',
    Wireframing = 'Wireframing',
    Prototyping = 'Prototyping',
  
    // Tools & IDEs
    VSCode = 'VS Code',
    IntelliJ = 'IntelliJ IDEA',
    WebStorm = 'WebStorm',
    PyCharm = 'PyCharm',
    Eclipse = 'Eclipse',
    NetBeans = 'NetBeans',
    Postman = 'Postman',
    Swagger = 'Swagger',
    Insomnia = 'Insomnia',
    Terminal = 'Terminal (CLI)',
    Zsh = 'Zsh',
    Tmux = 'Tmux',
  
    // Project & Productivity Tools
    Jira = 'Jira',
    Trello = 'Trello',
    Notion = 'Notion',
    Confluence = 'Confluence',
    Slack = 'Slack',
    MicrosoftTeams = 'Microsoft Teams',
    Zoom = 'Zoom',
    GitBook = 'GitBook',
  
    // Package Managers & Build Tools
    Npm = 'npm',
    Yarn = 'Yarn',
    PNPM = 'pnpm',
    Maven = 'Maven',
    Gradle = 'Gradle',
    Webpack = 'Webpack',
    ViteTool = 'Vite Tool',
    Babel = 'Babel',
  }
  